name: beauty_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

  provider: ^6.0.5

  # riverpod_annotation 추가
  riverpod_annotation: ^2.0.2

  #freezed 추가
  freezed:
  freezed_annotation:

  cupertino_icons: ^1.0.2

  # 라이브러리 추가
  dio: ^4.0.6
  json_annotation: ^4.4.0
  retrofit: ">=3.0.0 <4.0.0"
  skeletons: ^0.0.3
  go_router: ^7.0.0
  badges: ^2.0.3
  debounce_throttle: ^2.0.0
  flutter_secure_storage:
  camera:
  path_provider:
  path:
  image_picker:
  http_interceptor: ^1.0.0
  shared_preferences: ^2.0.6
  kakao_flutter_sdk_user:
  url_launcher: ^6.1.11
  percent_indicator: ^4.0.1
  spincircle_bottom_bar: 2.0.0
  material_design_icons_flutter: 7.0.7296



  kakao_flutter_sdk_talk:

  firebase_core:
  firebase_auth:
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  firebase_core_platform_interface: 4.5.1
  logger: ^1.3.0
  jwt_decoder: ^2.0.1


dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  retrofit_generator: ">=4.0.0 <5.0.0"
  cached_network_image: ^3.2.1
  provider: 6.0.5

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


fonts:
  - family: kufam
    fonts:
      - asset: assets/fonts/kufam/Kufam-Regular.ttf
      - asset: assets/fonts/kufam/Kufam-Medium.ttf
        weight: 500
      - asset: assets/fonts/kufam/Kufam-Bold.ttf
        weight: 700

  - family: noto_sans_kr
    fonts:
      - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.otf
      - asset: assets/fonts/noto_sans_kr/NotoSansKR-Light.otf
        weight: 300
      - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.otf
        weight: 500
      - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.otf
        weight: 700

  - family: montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
      - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700

