name: beauty_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #login
  flutter_naver_login :

  # dev
  flutter_hooks: ^0.18.6
  provider: ^6.0.5
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.0.2
  freezed:
  freezed_annotation:
  logger: ^1.3.0
  device_info_plus: ^9.0.3

  # data
  dio: ^4.0.6
  json_annotation: ^4.4.0
  retrofit: ">=3.0.0 <4.0.0"
  go_router: ^7.0.0
  debounce_throttle: ^2.0.0
  tuple: ^2.0.2
  intl: ^0.17.0

  # layout
  skeletons: ^0.0.3 #로딩 페이지
  badges: ^2.0.3 #뱃지 표현
  spincircle_bottom_bar: 2.0.0 #하단 써클 메뉴
  carousel_slider: #슬라이더
  dropdown_button2: #드롭 다운 커스텀 버전
  simple_shadow: ^0.3.1 #png 그림자
  flutter_layout_grid:
  flutter_screenutil: ^5.7.0
  animated_splash_screen: ^1.1.0

  percent_indicator: ^4.0.1 #원 그래프
  fl_chart: ^0.62.0 #차트

  # icon
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: 7.0.7296

  # camera
  camera:
  path_provider:
  path:
  image_picker:
  http_interceptor: ^1.0.0
  shared_preferences: ^2.0.6
  crop: ^0.4.0
  video_player: ^2.7.1

  # link
  url_launcher: ^6.1.11 #url 연결
  flutter_inappwebview: ^5.7.2+3 #웹뷰
  remedi_kopo: ^0.0.2 #카카오 주소 검색


  flutter_svg:

  # kakao
  kakao_flutter_sdk_user:
  kakao_flutter_sdk_talk:

  # login
  flutter_secure_storage:
  jwt_decoder: ^2.0.1

  firebase_core:
  firebase_auth:
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  firebase_core_platform_interface: 4.5.1

  fluttertoast:

  # 윈도우
  camera_windows: ^0.2.1+8


dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  retrofit_generator: ">=4.0.0 <5.0.0"
  cached_network_image: ^3.2.1
  provider: 6.0.5

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: kufam
      fonts:
        - asset: assets/fonts/kufam/Kufam-Regular.ttf
        - asset: assets/fonts/kufam/Kufam-Medium.ttf
          weight: 500
        - asset: assets/fonts/kufam/Kufam-Bold.ttf
          weight: 700

    - family: noto_sans_kr
      fonts:
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.otf
          weight: 700

    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700