// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCqq1_T9AEc8o3XHLc6JR1F9IImMEBrs',
    appId: '1:94333008654:web:6be323613b1f3843f3755f',
    messagingSenderId: '94333008654',
    projectId: 'beautycare-16fbe',
    authDomain: 'beautycare-16fbe.firebaseapp.com',
    storageBucket: 'beautycare-16fbe.appspot.com',
    measurementId: 'G-WHRX7CTLE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0I78THOlsj8PO0h-7ZidjsLld2m5y_ss',
    appId: '1:94333008654:android:d8add03605166498f3755f',
    messagingSenderId: '94333008654',
    projectId: 'beautycare-16fbe',
    storageBucket: 'beautycare-16fbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jORECvw_17tIkiTuuTrccAjyBF9oQek',
    appId: '1:94333008654:ios:89028fcb40a1b73af3755f',
    messagingSenderId: '94333008654',
    projectId: 'beautycare-16fbe',
    storageBucket: 'beautycare-16fbe.appspot.com',
    iosClientId:
        '94333008654-av9q51nt6n5c4v0gtc4kd73tmq6on938.apps.googleusercontent.com',
    iosBundleId: 'com.sqisoft.coiz.beautycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5jORECvw_17tIkiTuuTrccAjyBF9oQek',
    appId: '1:94333008654:ios:a5d29275dfdd7498f3755f',
    messagingSenderId: '94333008654',
    projectId: 'beautycare-16fbe',
    storageBucket: 'beautycare-16fbe.appspot.com',
    iosClientId:
        '94333008654-9aao32pscfl1trjtsh9pi8tg5e2nde4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautyCare',
  );
}
